CREATE TABLE app_user
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (user_id),
    CONSTRAINT unique_app_user_username UNIQUE (username)
);

CREATE TABLE refresh_tokens
(
    refresh_token_id UUID    NOT NULL,
    user_id BIGINT,
    token      VARCHAR(255)                NOT NULL,
    device_id  VARCHAR(255)                NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (refresh_token_id),
    CONSTRAINT unique_refresh_token_token UNIQUE (token),
    CONSTRAINT unique_refresh_token_device_id UNIQUE (device_id, user_id),
    CONSTRAINT fk_refresh_tokens_app_user FOREIGN KEY (user_id) REFERENCES app_user (user_id) ON DELETE CASCADE
);

CREATE INDEX idx_app_user_username ON app_user (username);
CREATE INDEX idx_refresh_tokens_device_id_token ON refresh_tokens (device_id, token);