CREATE TABLE api_keys
(
    api_key_id   bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    api_key_hash bytea       NOT NULL UNIQUE,
    name         varchar(50) NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now()
);
