openapi: 3.1.0
info:
  title: Pointeur Backend – Integration API
  description: |
    Read-only REST API for external integrations with the Pointeur scheduling
    application.  This surface requires an API key passed via the `X-Api-Key`
    header.

    **Constraints:**
    - Only `GET` requests are accepted; all other HTTP methods are denied.
    - Endpoints related to users and API key management are not available.
  version: 2.0.0
  contact:
    name: 2RK-dev

servers:
  - url: http://localhost:8080/integration
    description: Local development server

security:
  - apiKeyAuth: []

tags:
  - name: Levels
    description: Academic levels
  - name: Groups
    description: Student groups within levels
  - name: Teachers
    description: Teacher registry
  - name: Teaching Units
    description: Teaching unit (subject) registry
  - name: Rooms
    description: Room registry
  - name: Schedule
    description: Schedule queries

# ---------------------------------------------------------------------------
# Paths — read-only subset, all referenced from shared.yaml
# ---------------------------------------------------------------------------
paths:

  /levels:
    $ref: 'shared.yaml#/components/pathItems/listLevels'

  /levels/{levelId}:
    $ref: 'shared.yaml#/components/pathItems/getLevel'

  /levels/{levelId}/groups:
    $ref: 'shared.yaml#/components/pathItems/listGroupsByLevel'

  /levels/{levelId}/groups/{groupId}:
    $ref: 'shared.yaml#/components/pathItems/getGroup'

  /levels/{levelId}/teachingUnits:
    $ref: 'shared.yaml#/components/pathItems/listTeachingUnitsByLevel'

  /teachers:
    $ref: 'shared.yaml#/components/pathItems/listTeachers'

  /teachers/{teacherId}:
    $ref: 'shared.yaml#/components/pathItems/getTeacher'

  /teachingUnits:
    $ref: 'shared.yaml#/components/pathItems/listTeachingUnits'

  /teachingUnits/{unitId}:
    $ref: 'shared.yaml#/components/pathItems/getTeachingUnit'

  /rooms:
    $ref: 'shared.yaml#/components/pathItems/listRooms'

  /rooms/{roomId}:
    $ref: 'shared.yaml#/components/pathItems/getRoom'

  /rooms/available:
    $ref: 'shared.yaml#/components/pathItems/listAvailableRooms'

  /schedule:
    $ref: 'shared.yaml#/components/pathItems/getSchedule'

  /schedule/{scheduleItemId}:
    $ref: 'shared.yaml#/components/pathItems/getScheduleItem'

# ---------------------------------------------------------------------------
# Components
# ---------------------------------------------------------------------------
components:
  securitySchemes:
    apiKeyAuth:
      $ref: 'shared.yaml#/components/securitySchemes/apiKeyAuth'
