# rest.yaml — Frontend API specification.
# Paths compose HTTP methods by referencing operations from shared.yaml.
# No schemas or operations are defined locally.

openapi: 3.1.0
info:
  title: Pointeur Backend – Frontend API
  description: |
    REST API for the Pointeur scheduling application.
    This specification covers the **frontend-facing** surface.
    All endpoints require JWT Bearer authentication unless stated otherwise.
  version: 2.0.0
  contact:
    name: 2RK-dev

servers:
  - url: /api/v1
    description: Frontend API base path

# Global security — inherited by all operations that do not override it.
security:
  - bearerAuth: []

tags:
  - name: Authentication
    description: Login, logout, token refresh, and password management
  - name: Users
    description: User account management (SuperAdmin only)
  - name: API Keys
    description: API key management for the integration surface (SuperAdmin only)
  - name: Levels
    description: Academic levels
  - name: Groups
    description: Student groups within levels
  - name: Teachers
    description: Teacher registry
  - name: Teaching Units
    description: Teaching unit (subject) registry
  - name: Rooms
    description: Room registry and availability
  - name: Schedule
    description: Schedule item management
  - name: Import
    description: Bulk data import
  - name: Export
    description: Data export

# ---------------------------------------------------------------------------
# Paths — each HTTP method $refs the corresponding operation from shared.yaml
# ---------------------------------------------------------------------------
paths:

  # ── Authentication ───────────────────────────────────────────────────────
  /auth/login:
    post:
      $ref: 'shared.yaml#/components/x-operations/login'

  /auth/me:
    get:
      $ref: 'shared.yaml#/components/x-operations/getCurrentUser'

  /auth/refresh:
    post:
      $ref: 'shared.yaml#/components/x-operations/refreshToken'

  /auth/logout:
    post:
      $ref: 'shared.yaml#/components/x-operations/logout'

  /auth/password:
    put:
      $ref: 'shared.yaml#/components/x-operations/changePassword'

  # ── Users ────────────────────────────────────────────────────────────────
  /users:
    get:
      $ref: 'shared.yaml#/components/x-operations/listUsers'
    post:
      $ref: 'shared.yaml#/components/x-operations/createUser'

  /users/{userId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getUser'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteUser'

  # ── API Keys ─────────────────────────────────────────────────────────────
  /api-keys:
    get:
      $ref: 'shared.yaml#/components/x-operations/listApiKeys'
    post:
      $ref: 'shared.yaml#/components/x-operations/createApiKey'

  /api-keys/{apiKeyId}:
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteApiKey'

  # ── Levels ───────────────────────────────────────────────────────────────
  /levels:
    get:
      $ref: 'shared.yaml#/components/x-operations/listLevels'
    post:
      $ref: 'shared.yaml#/components/x-operations/createLevel'

  /levels/{levelId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getLevel'
    put:
      $ref: 'shared.yaml#/components/x-operations/updateLevel'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteLevel'

  # ── Groups ───────────────────────────────────────────────────────────────
  /levels/{levelId}/groups:
    get:
      $ref: 'shared.yaml#/components/x-operations/listGroupsByLevel'
    post:
      $ref: 'shared.yaml#/components/x-operations/createGroup'

  /levels/{levelId}/groups/{groupId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getGroup'
    put:
      $ref: 'shared.yaml#/components/x-operations/updateGroup'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteGroup'

  # ── Teachers ─────────────────────────────────────────────────────────────
  /teachers:
    get:
      $ref: 'shared.yaml#/components/x-operations/listTeachers'
    post:
      $ref: 'shared.yaml#/components/x-operations/createTeacher'

  /teachers/{teacherId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getTeacher'
    put:
      $ref: 'shared.yaml#/components/x-operations/updateTeacher'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteTeacher'

  # ── Teaching Units ───────────────────────────────────────────────────────
  /teachingUnits:
    get:
      $ref: 'shared.yaml#/components/x-operations/listTeachingUnits'
    post:
      $ref: 'shared.yaml#/components/x-operations/createTeachingUnit'

  /teachingUnits/{unitId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getTeachingUnit'
    put:
      $ref: 'shared.yaml#/components/x-operations/updateTeachingUnit'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteTeachingUnit'

  /levels/{levelId}/teachingUnits:
    get:
      $ref: 'shared.yaml#/components/x-operations/listTeachingUnitsByLevel'

  # ── Rooms ────────────────────────────────────────────────────────────────
  /rooms:
    get:
      $ref: 'shared.yaml#/components/x-operations/listRooms'
    post:
      $ref: 'shared.yaml#/components/x-operations/createRoom'

  /rooms/{roomId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getRoom'
    put:
      $ref: 'shared.yaml#/components/x-operations/updateRoom'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteRoom'

  /rooms/available:
    get:
      $ref: 'shared.yaml#/components/x-operations/listAvailableRooms'

  # ── Schedule ─────────────────────────────────────────────────────────────
  /schedule:
    get:
      $ref: 'shared.yaml#/components/x-operations/getSchedule'
    post:
      $ref: 'shared.yaml#/components/x-operations/createScheduleItem'

  /schedule/batch:
    post:
      $ref: 'shared.yaml#/components/x-operations/createScheduleItemsBatch'

  /schedule/{scheduleItemId}:
    get:
      $ref: 'shared.yaml#/components/x-operations/getScheduleItem'
    put:
      $ref: 'shared.yaml#/components/x-operations/updateScheduleItem'
    delete:
      $ref: 'shared.yaml#/components/x-operations/deleteScheduleItem'

  # ── Export ───────────────────────────────────────────────────────────────
  /export:
    get:
      $ref: 'shared.yaml#/components/x-operations/exportData'

  # ── Import ───────────────────────────────────────────────────────────────
  /import/upload:
    post:
      $ref: 'shared.yaml#/components/x-operations/importData'

# ---------------------------------------------------------------------------
# Components — security scheme referenced from shared.yaml
# ---------------------------------------------------------------------------
components:
  securitySchemes:
    bearerAuth:
      $ref: 'shared.yaml#/components/securitySchemes/bearerAuth'
